### ISSUE TITLE
Invalid date exception when running import_statistics_data

### ISSUE THREAD

**Issue by marklit** [toddwschneider/nyc-taxi-data#14]
After downloading and importing all the data and running:

```bash
./import_trip_data.sh
./import_uber_trip_data.sh
cat analysis/prepare_analysis.sql \
      tlc_statistics/create_statistics_tables.sql | \
      psql nyc-taxi-data
```

I ran the `import_statistics_data.rb` script:

```bash
$ ruby tlc_statistics/import_statistics_data.rb
```

And it resulted in the following:

```
tlc_statistics/import_statistics_data.rb:16:in `strptime': invalid date (ArgumentError)
        from tlc_statistics/import_statistics_data.rb:16:in `block (2 levels) in <main>'
        from tlc_statistics/import_statistics_data.rb:14:in `each'
        from tlc_statistics/import_statistics_data.rb:14:in `block in <main>'
        from /usr/lib/ruby/1.9.1/csv.rb:1354:in `open'
        from tlc_statistics/import_statistics_data.rb:13:in `<main>'
```

**Comment by marklit** [comment]
It looks like the month and the year were swapped in the source file:

```bash
$ curl "http://www.nyc.gov/html/tlc/downloads/csv/data_reports_monthly_indicators_yellow.csv"                                                                                                                
```

```
Month/Year,Trips Per Day,Farebox Per Day,Unique Drivers,Unique Medallions,Medallions Per Day,Avg Days Medallions on Road,Avg Hours Per Day Per Medallion,Avg Days Drivers on Road,Avg Hours Per Day Per Driver,Avg Minutes Per Trip,Percent of Trips Paid with Credit Card
16-Apr,"397,780","5,721,501","30,488","13,370","12,875",28.9,,21.7,,17.4,67%
16-Mar,"393,886","5,614,089","30,327","13,379","12,828",29.7,,22.2,,15,67%
16-Feb,"392,470","5,427,875","29,564","13,339","12,718",27.7,,20.8,,14.6,67%
...
```

When I patch the ruby file with the following:

```diff
diff --git a/tlc_statistics/import_statistics_data.rb b/tlc_statistics/import_statistics_data.rb
index fe1634e..269a884 100644
--- a/tlc_statistics/import_statistics_data.rb
+++ b/tlc_statistics/import_statistics_data.rb
@@ -13,7 +13,7 @@ yellow_monthly_data.shift
 CSV.open("yellow_monthly_data.csv", "wb") do |csv|
   yellow_monthly_data.each do |row|
     csv << [
-      Date.strptime(row[0], "%B-%y").end_of_month,
+      Date.strptime(row[0], "%y-%B").end_of_month,
       row[1].gsub(",", "").to_i,
       row[2].gsub(",", "").to_i,
       row[3].gsub(",", "").to_i,
```

It runs but reports the following:

```
create_statistics_tables.sql: No such file or directory
COPY 76
COPY 22391
```

**Comment by toddwschneider** [comment]
Fixed by https://github.com/toddwschneider/nyc-taxi-data/pull/18
